### ISSUE TITLE
Upgrade `joi`

### ISSUE THREAD

**Issue by HsuTing** [shellscape/koa-webpack#113]
> The Issues page for this repository is not a support forum, it is for reporting potential bugs in this module, which
[composes](https://github.com/koajs/compose) webpack-hot-middleware and webpack-dev-middle for use with koa2.
If you have arrived here because you cannot get [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middlewar)
or [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware/) working, please review the documentation
for the respective middleware you are experiencing a problem with. If you proceed with this form, please fill out *_all_* fields, or your issue may be closed as "invalid." Please remove this header to acknowledge this message.

* Node Version: v11.12.0
* NPM Version: v6.9.0
* koa Version: v2.7.0
* koa-wepback Version: v5.2.2

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

```js
// webpack.config.js
```

```js
// app.js
```

### Expected Behavior
No warning

### Actual Behavior
```sh
warning koa-webpack > joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning koa-webpack > joi > topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning koa-webpack > joi > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning koa-webpack > joi > topo > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
```

### How can we reproduce the behavior?
```sh
yarn add koa-webpack
```

**Comment by shellscape** [comment]
This is a non-issue as warnings do not hamper functionality. koa-webpack gets periodic dependency updates, and this will likely be resolved then.
