### ISSUE TITLE
How to use the package in typescript?

### ISSUE THREAD

**Issue by budarin** [shellscape/koa-webpack#124]
There is now top level await for common.js modules (which is node app) in TypeScript

How to use it in code with TypeScript?

**Comment by shellscape** [comment]
I'm not really sure what you're asking, but this package doesn't use top level await. If you're asking how to use this package in TS, then I'd refer you to ES6 import fundamentals. MDN has good info on that.

**Comment by budarin** [comment]
`const middleware = await koaWebpack({ compiler });` - it's a top level async call

**Comment by shellscape** [comment]
That's an example of how to use the export method. It's not telling you to use a top-level await. This package's job is not to give you a full implementation as an example. You must understand how to use Koa.
