### ISSUE TITLE
unable to import koa-webpack into lerna monorepo

### ISSUE THREAD

**Issue by noahehall** [shellscape/koa-webpack#127]
`import koaWebpack from 'koa-webpack'`
`Error: Cannot find module 'webpack/lib/ParserHelpers'`

try yourself:
1. [clone nodeproto](https://github.com/noahehall/nodeproto)
2. [checkout this commit](https://github.com/noahehall/nodeproto/tree/078ac99bbd5cbf74f11747e6782ab3c8e60e37a5)
3. run `npm run lerna:run client`

[server.mjs has the relevant code](https://github.com/noahehall/nodeproto/blob/078ac99bbd5cbf74f11747e6782ab3c8e60e37a5/packages/client/bff/server.mjs)

**Comment by shellscape** [comment]
Removing the issue template isn't cool.
