### ISSUE TITLE
unable to import koa-webpack in lerna monorepo

### ISSUE THREAD

**Issue by noahehall** [shellscape/koa-webpack#128]
* Node Version: `16.2`
* NPM Version: `7.13.0`
* koa Version: `2.13.1`
* koa-wepback Version: `6.0.0`

`import koaWebpack from 'koa-webpack'`
`Error: Cannot find module 'webpack/lib/ParserHelpers'`
[server.mjs has the relevant code](https://github.com/noahehall/nodeproto/blob/078ac99bbd5cbf74f11747e6782ab3c8e60e37a5/packages/client/bff/server.mjs)

### Expected Behavior
- i can import koa-webpack

### Actual Behavior
- i cannot import koa-webpack
### How can we reproduce the behavior?

1. [clone nodeproto](https://github.com/noahehall/nodeproto)
2. [checkout this commit](https://github.com/noahehall/nodeproto/tree/078ac99bbd5cbf74f11747e6782ab3c8e60e37a5)
3. run `npm run lerna:run client`

**Comment by noahehall** [comment]
doesnt support webpack5
https://github.com/shellscape/koa-webpack/issues/126

**Comment by shellscape** [comment]
https://github.com/shellscape/koa-webpack/blob/1271612ed1f7fa701b463c20d5005c36a744509b/package.json#L29-L31

**Comment by noahehall** [comment]
[i win](https://github.com/noahehall/koa-webpack/blob/a444dbc02fa3aaea6ecc9ebc1e406c64448e50b1/package.json#L30)
