### ISSUE TITLE
Non-Existent Resources Have No Response

### ISSUE THREAD

**Issue by changchengqin** [shellscape/koa-webpack#14]
As noticed in #4 ,paths、assets which koa don't handle or don't exist ,don't generate the correct server response. No response code is sent, and the response just hangs.
github test repo is [here](https://github.com/changchengqin/koa_webpack_demo_one).
the procedure is below:
1.koa2 entry js
![image](https://cloud.githubusercontent.com/assets/3336443/20959623/dc8cc680-bc96-11e6-805b-d9292f5e73b1.png)

2.webpack 2 config js
![image](https://cloud.githubusercontent.com/assets/3336443/20959659/1ccb8d80-bc97-11e6-9cdb-0187ad10f674.png)

3.client entry js
![image](https://cloud.githubusercontent.com/assets/3336443/20959678/2dda2884-bc97-11e6-9190-1673f8025998.png)

4.effect
![hangs](https://cloud.githubusercontent.com/assets/3336443/20960339/e64d5d16-bc9a-11e6-8421-8b3f8d2fb00d.gif)

**Comment by JounQin** [comment]
It is always pending when calling a Non-Existent url and do not return 404 either. :(

Please deal with it as soon as possible.

**Comment by shellscape** [comment]
@JounQin something probably got lost in translation there - that seems a little pushy :) I'd be happy to review a pull request for the issue you're seeing.
