### ISSUE TITLE
application/octet-stream

### ISSUE THREAD

**Issue by daryl** [shellscape/koa-webpack#15]
Unless I set a header, it's forcing `application/octet-stream`, which causes my page to download.

```js
app.use(async (ctx) => {
  ctx.res.setHeader('Content-Type', 'text/html');
  ctx.body = '...';
});
```

Can this be avoided?

**Comment by shellscape** [comment]
This is more likely a symptom of koa2 rather than koa-webpack. When you run the app in production mode, without koa-webpack, do you get the same issue? If so, then it's koa2. If not, then it's koa-webpack.

**Comment by shellscape** [comment]
Try adding `headers` to your `dev` config. eg:

```js
    dev: {
      publicPath: config.output.publicPath,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
      stats: { colors: true },
      quiet: false,
      noInfo: true
    },
```
