### ISSUE TITLE
How can I use webpack html plugin in your koa-webpack

### ISSUE THREAD

**Issue by linxiaowu66** [shellscape/koa-webpack#18]
Hi @shellscape ,
   in koa v1, I implement this webpack hot middleware as following:
```
  const webpack = require('webpack')
  const webpackConfig = require('../webpack/webpack.config.js')

  const compiler = webpack(webpackConfig)
  const middleware = require('webpack-dev-middleware')(compiler, {
    publicPath: webpackConfig.output.publicPath,
    contentBase: 'src',
    stats: {
      colors: true,
      hash: false,
      timings: true,
      chunks: false,
      chunkModules: false,
      modules: false
    }
  })

  app.use(middleware)
  const hotMiddleware = require('webpack-hot-middleware')(compiler)
  // force page reload when html-webpack-plugin template changes
  compiler.plugin('compilation', (compilation) => {
    compilation.plugin('html-webpack-plugin-after-emit', (data, cb) => {
      hotMiddleware.publish({ action: 'reload' })
      cb()
    })
  })
  app.use(hotMiddleware)
```

But now with your plugin, the hotMiddleware is not single export any more, how can i configure the event of html-webpack-plugin-after-emit ?

Thanks a lot

**Comment by shellscape** [comment]
If you're looking to configure the webpack-hot-middleware plugin, you can do so by passing the same config object to the `hot` property of the config for koa-webpack. see: https://github.com/shellscape/koa-webpack#hot

**Comment by linxiaowu66** [comment]
@shellscape this option can be config the function ?
 Can you give me an example ?
 Thanks.

**Comment by shellscape** [comment]
The options are the same as are listed here: https://github.com/glenjamin/webpack-hot-middleware

I'm sorry but I don't understand what your first question is.

**Comment by linxiaowu66** [comment]
@shellscape  how can I use these code to your `hot` option?

```
compiler.plugin('compilation', (compilation) => {
    compilation.plugin('html-webpack-plugin-after-emit', (data, cb) => {
      hotMiddleware.publish({ action: 'reload' })
      cb()
    })
  })
```

**Comment by shellscape** [comment]
you cannot at the moment. I can export that in a future release if you need to access the `hotMiddleware` instance.

**Comment by linxiaowu66** [comment]
ok, Thanks a lot

**Comment by shellscape** [comment]
0.2.1 exposes both composed middlewares. https://github.com/shellscape/koa-webpack#access-to-webpack-hot-middleware-and-webpack-dev-middleware

**Comment by linxiaowu66** [comment]
Thanks
