### ISSUE TITLE
Shrinkwrap fails: Webpack 2.2.0 has been released

### ISSUE THREAD

**Issue by NikkiDreams** [shellscape/koa-webpack#19]
peer invalid: webpack@~2.1.0-beta.27, required by koa-webpack@0.1.10

**Comment by shellscape** [comment]
thanks for the heads up

**Comment by shellscape** [comment]
https://github.com/shellscape/koa-webpack/commit/bbc0a074635f89340eae002e0c1bb0f8046f7092 fixes this. 0.2.0 published
