### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by PredokMiF** [shellscape/koa-webpack#20]
Hi! Can you add link to simple project on github with this middleware: koa2, webpack2 and React (for example, I can help with it). Yesterday I couldn't setup it together.

**Comment by shellscape** [comment]
Here's the `app.js` file from a simple app we use koa-webpack in:

```js
'use strict';

import 'colors';
import Koa from 'koa';
import bodyParser from 'koa-bodyparser';
import serve from 'koa-static';
import devWare from 'koa-webpack';

import sockets from './sockets';
import config from './webpack.config.js';

const app = new Koa(),
  port = 3000;

sockets(app);

app
  .use(bodyParser())
  .use(serve(`${__dirname}/public`))
  .use(serve(`${__dirname}/dist`))

  .use(devWare({
    dev: {
      // publicPath: config.output.publicPath,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
      stats: { colors: true },
      quiet: false,
      noInfo: true
    },
    hot: {
      log: console.log,
      path: '/__webpack_hmr',
      heartbeat: 10 * 1000
    }
  }))

  .listen(port, () => {
    console.log('Server Started ∹'.green, 'http://localhost:'.grey + port.toString().blue);
  });

export default app;
```

You'll have to use node 7+ and launch this app with the `--harmony` flag, use babel, or use [harmonica](https://www.npmjs.com/package/harmonica) with node 7+.

I'm sorry, we don't use React so you're on your own with that bit.

Beyond this snippet, I'd happily accept a PR with a larger example, that meets linting requirements.

**Comment by PredokMiF** [comment]
I wrote simple example app, but hot reload is not workink, I dont now why (
