### ISSUE TITLE
Non-Existent Assets Have No Response

### ISSUE THREAD

**Issue by shellscape** [shellscape/koa-webpack#4]
As noticed by @christensson, assets (js, images, css, etc) which don't exist don't generate the correct server response. No response code is sent, and the response just hangs.

> Let's say that I setup the webpack configuration to dynamically serve /js/bundle.js which is referenced from index.html which is statically served from another middleware. I found out that if I do a curl for localhost:/js/bundle2.js which webpack isn't setup to dynamically serve nothing happens, no response is returned, no 404, no nothing....

**Comment by lostpebble** [comment]
This sounds like it might be the same issue that I'm facing now. I'm getting no response for resources on my server. I'm using the newest version `0.1.7.`

So the previous issue is now solved, in that it waits for webpack to compile before displaying the page. This middleware works fine for everything if we load the page before webpack has finished compiling. But when I try and reload the page, or request resources dynamically from the server, they do not respond any more. From my logs it seems they get to the point of the bubbling phase, going back into the webpack middleware but then no further.

It appears the middleware is somehow hijacking resource requests it should have nothing to do with. The files webpack is setup to serve such as `bundle.js` still work fine though.

**Comment by shellscape** [comment]
merged @lostpebble 's PR and tested, looks like everything works well. refactored a tad and added some comments, published 0.1.8.

**Comment by lemieux** [comment]
:ok_hand: @shellscape

**Comment by changchengqin** [comment]
This sounds like it might be the same issue that I'm facing now. I'm getting no response for resources on my server. I'm using the newest version 0.1.9.

**Comment by shellscape** [comment]
@changchengqin testing here and is working as expected. might need some debugging from your end.
