### ISSUE TITLE
await ctx.render 404

### ISSUE THREAD

**Issue by xyezir** [shellscape/koa-webpack#40]
```javascript
await dev(context.req, {
      end: (content) => {
        context.body = content;
      },
      setHeader: context.set.bind(context),
      locals: context.state
    }, next);
```

```javascript
shared.handleRequest(filename, processRequest, req);
```

webpack-dev-middleware is not return Promise, koa.use middleware, koa next await is broken.

**Comment by shellscape** [comment]
> If you proceed with this form, please fill out *_all_* fields, or your issue may be closed as "invalid."

The issue template isn't optional.
