### ISSUE TITLE
Build of 0.5.0 does not contain recent changes

### ISSUE THREAD

**Issue by dpatti** [shellscape/koa-webpack#50]
* Node Version: v7.9.0
* NPM Version: v4.2.0
* koa-wepback Version: v0.5.0

To illustrate:

```
$ npm view koa-webpack@0.4 dist.tarball | xargs curl -s | tar -xzO package/dist/index.js | md5sum
d41d8cd98f00b204e9800998ecf8427e  -
$ npm view koa-webpack@0.5 dist.tarball | xargs curl -s | tar -xzO package/dist/index.js | md5sum
d41d8cd98f00b204e9800998ecf8427e  -
```

The `dist/index.js` file from the package tarball is the same in 0.5 as it was in 0.4. This means it's missing the changes from #49.

**Comment by shellscape** [comment]
thanks for the heads up on that. looking into it now

**Comment by shellscape** [comment]
0.5.1 should fix that. doesn't look like dist made it into the commit. cheers
