### ISSUE TITLE
Request for webpack-hot-server-middleware to be incorporated

### ISSUE THREAD

**Issue by roastlechon** [shellscape/koa-webpack#66]
Just a feature suggestion to also incorporate `webpack-hot-server-middleware`

**Comment by roastlechon** [comment]
Related issue: https://github.com/60frames/webpack-hot-server-middleware/issues/28

**Comment by shellscape** [comment]
The issue template isn't optional. Closed as invalid.

**Comment by roastlechon** [comment]
@shellscape is it not possible to have an issue as an enhancement/feature request? I do not see anything in the issue template that denotes that type of issue.

**Comment by pho3nixf1re** [comment]
I re-opened this via #105 with more details and possible solutions.
