### ISSUE TITLE
Error: Cannot find module 'babel-runtime/core-js/object/assign'

### ISSUE THREAD

**Issue by JounQin** [shellscape/koa-webpack#74]
* Node Version: 9.3.0
* NPM Version: 5.6.0
* koa Version: 2.4.1
* koa-wepback Version: 1.0.0

### Expected Behavior

Works well without babel, I'm using typescript, so babel is unnecessary

### Actual Behavior

Throw error unless I install `babel-runtime` manually

### How can we reproduce the behavior?

https://github.com/JounQin/graphql-study

remove `babel-runtime` dependency, then `yarn dev`.

add `babel-runtime` as `koa-webpack` dependency should fix this, or find another way.

**Comment by shellscape** [comment]
2.0.0 removed babel as a runtime dependency.
