### ISSUE TITLE
koa-webpack 5.* on egg framework of koa2 can not work

### ISSUE THREAD

**Issue by my9074** [shellscape/koa-webpack#93]
> The Issues page for this repository is not a support forum, it is for reporting potential bugs in this module, which
[composes](https://github.com/koajs/compose) webpack-hot-middleware and webpack-dev-middle for use with koa2.
If you have arrived here because you cannot get [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middlewar)
or [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware/) working, please review the documentation
for the respective middleware you are experiencing a problem with. If you proceed with this form, please fill out *_all_* fields, or your issue may be closed as "invalid." Please remove this header to acknowledge this message.

* Node Version: 8.11.1
* NPM Version: 5.6.0
* koa Version: 2
* koa-wepback Version: 5.0.2

### Actual Behavior
My koa framwork is [egg](https://eggjs.org/) . I update koa-webpack 3.* to 5.0.2,  koa-webpack can not work.  but i can not find reason with debug ( koa-webpack 3.* is ok ).

<img width="1414" alt="wx20180616-194857 2x" src="https://user-images.githubusercontent.com/4555635/41498395-11087ba2-719f-11e8-954e-25a9484eebf4.png">
And this is my egg config of koa-webpack 5.*:
<img width="615" alt="wx20180616-194938 2x" src="https://user-images.githubusercontent.com/4555635/41498398-21e24962-719f-11e8-9ab3-3867e08060d6.png">

On koa-webpack 3.* it ok.
<img width="511" alt="wx20180616-195752 2x" src="https://user-images.githubusercontent.com/4555635/41498410-a56b1836-719f-11e8-96cd-611aa27c6acb.png">
<img width="445" alt="wx20180616-195809 2x" src="https://user-images.githubusercontent.com/4555635/41498414-b24be788-719f-11e8-80a9-c5c67071bc9b.png">

**Comment by shellscape** [comment]
Please don't use screenshots when you could simply use code blocks and copy the code. 

This is also not a support forum, as the header of the issue template indicates. There are always breaking changes between major versions, and you should read the change list and breaking changes for each major version on the _Releases_ page.
