### ISSUE TITLE
Module not found: Error: Can't resolve 'webpack-hot-client/client?

### ISSUE THREAD

**Issue by lgwebdream** [shellscape/koa-webpack#96]
Everything else seems to be working fine, but the following error was reported. My entry is similar to this {
   Index:["index.ts"]
} In anxiety, I hope you can point me awry.
 "webpack": "^4.14.0",
"webpack-cli": "^3.0.8",
"koa-webpack": "^5.0.2",
ERROR in multi webpack-hot-client/client?51a207ab-5368-4dd3-ae13-c976b884cece ./src/webapp/views/index/index-index.entry.ts
Module not found: Error: Can't resolve 'webpack-hot-client/client?51a207ab-5368-4dd3-ae13-c976b884cece' in '/Users/yuanzhijia/Desktop/childcode'
 @ multi webpack-hot-client/client?51a207ab-5368-4dd3-ae13-c976b884cece ./src/webapp/views/index/index-index.entry.ts

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.
